### ISSUE TITLE
Separation of image server

### ISSUE THREAD

**Issue by kerim1** [archival-IIIF/image-server-core#1]
Why is the image server now separated across two different repositories on GitHub? I don't really see the point of it and I don't like it either. 

1. Why would we need a library for this?
2. And if you want to make this an NPM package, why can't it be done on a single repository?

**Comment by kerim1** [comment]
For now I moved my changes to a separate branch on the image server: https://github.com/archival-IIIF/image-server/commits/master-iish

**Comment by Sozialarchiv** [comment]
> Why would we need a library for this?

I wanted to have a npm package without koa dependency. See:

E.g.:

https://github.com/archival-IIIF/test-server
https://github.com/archival-IIIF/demo

> And if you want to make this an NPM package, why can't it be done on a single repository?

it seemed better that way. But if you prefer on repository, then feel free to change that.

**Comment by kerim1** [comment]
Okay, let's keep it separated. But I would like to keep as much of the git history as possible. So I have been merging the old history of the other repository into this history. Both main/master branches of this repo and the image server have now been updated with the merged history. Also I merged all the changes I made up this far, so I thought it was fair to release it as version 2.0.0.

**Comment by kerim1** [comment]
Because of the merging and changes of the git history, you will probably have to reset your local git repo as well or you'll run into problems.

**Comment by Sozialarchiv** [comment]
Thank you.

**Comment by kerim1** [comment]
I had some time to rework the image server https://github.com/archival-IIIF/image-server in order to remove the Koa dependency and use the default HTTP web server implementation of NodeJS instead. Now it has no more external dependencies (except for `dotenv` for the environment variables). 
Maybe now we could reintegrate the web server back into this repository? The Koa dependency was the real reason to separate those code bases. But now without the dependency you have the choice to run the image web server that comes with it or just call the `serveImage` if you integrate it in another NodeJS project (like you did for `test-server` and `demo`) without bringing in extra unnecessary dependencies.

**Comment by Sozialarchiv** [comment]
> Maybe now we could reintegrate the web server back into this repository? 

That sounds fine for me. Thank you for your work.

**Comment by kerim1** [comment]
Back into this repository and also replaced the environment variables with arguments allowing for exactly no new dependencies.
