### ISSUE TITLE
bump sharp version

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/image-server-core#2]
@kerim1  Is there a reason why sharp is fixed to 0.32.5?
https://github.com/archival-IIIF/image-server-core/blob/main/package.json#L11

There is a CVE for sharp < 0.32.6.
https://github.com/advisories/GHSA-54xq-cgqr-rpm3

Wouldn't it be better to use something like ^0.32.5..

**Comment by kerim1** [comment]
I prefer fixed versions as it is much clearer what versions are used and it causes less problems (read incompatibilities). 

Concerning the CVE: the vulnerability lies with using untrusted WebP input, which is not the case for how Sharp is used within this package. However, I was already working on a dependencies update, which I just pushed to GitHub / NPM. :-)

**Comment by Sozialarchiv** [comment]
Thanks a lot.
